#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

feign:
  endpoints:
    org.seedstack.feign.fixtures.apis.TestAPI:
      baseUrl: http://localhost:${sys.tomcat\.http\.port:'9090'}/feign
      logLevel: BASIC
      fallback: org.seedstack.feign.fixtures.TestFallback
      logger: feign.slf4j.Slf4jLogger
      hystrixWrapper: AUTO
    org.seedstack.feign.fixtures.apis.TestContractAPI:
      baseUrl: http://localhost:${sys.tomcat\.http\.port:'9090'}/feign
      contract: org.seedstack.feign.fixtures.TestContract
      hystrixWrapper: DISABLED
    org.seedstack.feign.fixtures.apis.HystrixEnabledAPI:
      baseUrl: http://localhost:${sys.tomcat\.http\.port:'9090'}/feign
      logLevel: BASIC
      fallback: org.seedstack.feign.fixtures.TestFallback
      hystrixWrapper: ENABLED
    org.seedstack.feign.fixtures.apis.HystrixDisabledAPI:
      baseUrl: http://localhost:${sys.tomcat\.http\.port:'9090'}/feign
      logLevel: BASIC
      hystrixWrapper: DISABLED  
    org.seedstack.feign.fixtures.apis.TargetableAPI:
      baseUrl: http://ignore.is.overriden
      logLevel: BASIC
      encoder: feign.jackson.JacksonEncoder
      decoder: feign.jackson.JacksonDecoder
      target: org.seedstack.feign.fixtures.TestTarget
      hystrixWrapper: DISABLED
      